module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "enemy_bullet_1.png",
				spriteColorRect = { x = 2, y = 2, width = 12, height = 28 }, 
				textureRect = { x = 28, y = 0, width = 12, height = 28 }, 
				spriteSourceSize = { width = 16, height = 32 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "enemy_bullet_2.png",
				spriteColorRect = { x = 2, y = 2, width = 12, height = 28 }, 
				textureRect = { x = 14, y = 0, width = 12, height = 28 }, 
				spriteSourceSize = { width = 16, height = 32 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "enemy_bullet_3.png",
				spriteColorRect = { x = 2, y = 2, width = 12, height = 28 }, 
				textureRect = { x = 0, y = 0, width = 12, height = 28 }, 
				spriteSourceSize = { width = 16, height = 32 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "enemy_bullet_4.png",
				spriteColorRect = { x = 2, y = 2, width = 12, height = 28 }, 
				textureRect = { x = 42, y = 0, width = 12, height = 28 }, 
				spriteSourceSize = { width = 16, height = 32 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end