module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "player_1.png",
				spriteColorRect = { x = 7, y = 11, width = 16, height = 44 }, 
				textureRect = { x = 58, y = 0, width = 16, height = 44 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "player_2.png",
				spriteColorRect = { x = 8, y = 12, width = 16, height = 44 }, 
				textureRect = { x = 76, y = 0, width = 16, height = 44 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "player_3.png",
				spriteColorRect = { x = 8, y = 9, width = 16, height = 46 }, 
				textureRect = { x = 20, y = 48, width = 16, height = 46 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "player_4.png",
				spriteColorRect = { x = 6, y = 8, width = 20, height = 46 }, 
				textureRect = { x = 0, y = 0, width = 20, height = 46 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "player_5.png",
				spriteColorRect = { x = 5, y = 11, width = 18, height = 44 }, 
				textureRect = { x = 38, y = 48, width = 18, height = 44 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "player_6.png",
				spriteColorRect = { x = 7, y = 12, width = 16, height = 44 }, 
				textureRect = { x = 40, y = 0, width = 16, height = 44 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "player_7.png",
				spriteColorRect = { x = 8, y = 9, width = 16, height = 46 }, 
				textureRect = { x = 22, y = 0, width = 16, height = 46 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "player_8.png",
				spriteColorRect = { x = 8, y = 8, width = 18, height = 46 }, 
				textureRect = { x = 0, y = 48, width = 18, height = 46 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end