module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "zombie_1.png",
				spriteColorRect = { x = 3, y = 18, width = 26, height = 36 }, 
				textureRect = { x = 28, y = 42, width = 26, height = 36 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_2.png",
				spriteColorRect = { x = 3, y = 16, width = 26, height = 38 }, 
				textureRect = { x = 56, y = 40, width = 26, height = 38 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_3.png",
				spriteColorRect = { x = 3, y = 15, width = 26, height = 40 }, 
				textureRect = { x = 0, y = 0, width = 26, height = 40 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_4.png",
				spriteColorRect = { x = 3, y = 18, width = 26, height = 36 }, 
				textureRect = { x = 0, y = 42, width = 26, height = 36 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_5.png",
				spriteColorRect = { x = 3, y = 16, width = 26, height = 38 }, 
				textureRect = { x = 56, y = 0, width = 26, height = 38 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_6.png",
				spriteColorRect = { x = 3, y = 15, width = 26, height = 40 }, 
				textureRect = { x = 28, y = 0, width = 26, height = 40 }, 
				spriteSourceSize = { width = 32, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end